### ISSUE TITLE
doc.querySelector(".social-count")?.textContent error

### ISSUE THREAD

**Issue by dronov-dmitry** [hieunc229/copilot-clone#54]
Hi, i have some problem.
Can you help me please?

Argument of type 'string | null | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.

![изображение](https://user-images.githubusercontent.com/9892891/153727140-560cce41-fefd-486c-a1a9-a753bc98869f.png)

**Comment by hieunc229** [comment]
Hi @dronov-dmitry, it's a typescript error (duplicate #48). Probably happens in the recent version of typescript). Does it still run when you start debugging?

If you can still debug and run the extension, just ignore the error. I'll make an update to fix those errors soon!

**Comment by dronov-dmitry** [comment]
Sorry, its not the same problem, as you can see at the picture debugger throw me only one error.

I make all that tell Asim, https://github.com/hieunc229/copilot-clone/issues/48#issuecomment-997348741

But it not help 

Can you help me
How can i fix that
Thx

**Comment by dronov-dmitry** [comment]
Today i see second error message
![изображение](https://user-images.githubusercontent.com/9892891/153747412-74e76611-875a-49af-8ecf-02ed6e12d5cf.png)
File extension.ts not found
Very strange

**Comment by dronov-dmitry** [comment]
Ok. Thx. I`ll be waiting. Good luck! :)

**Comment by hieunc229** [comment]
The error showing is the TypeError (not the same error message, but its complaints about the type definition). You can ignore it (since Captain Stack is using a new API, the dev team changes its type definition quite often and the plugin should still compile).

Though, I dig a little more. Turn out it also made some changes recently. After installing Captain Stack as our instruction, you can follow this answer for the recent fix. https://github.com/microsoft/vscode/issues/124024#issuecomment-985328059

I'll make some changes based on this update

**Comment by koskrit** [comment]
It's a type-safe error for older versions of Typescript, due to the use of optional chaining `.?` that could return undefined.
Bypassed it by making sure `parseInt` will always take a string:
```javascript
const socialCount : string = doc.querySelector(".social-count")?.textContent?.toString() || ""

        if (!snippet) return [];

        const item: SnippetResult = {
            votes: parseInt(socialCount),
            code: cleanContent(snippet),
            sourceURL: options.url,
            hasCheckMark: false
        };
```
